version: '3.8'

services:
  backend:
    build:
      context: ./blocker
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./blocker:/app
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
