version: '3.8'

services:
  backend:
    depends_on:
      - mongodb
    build:
      context: ./blocker
    ports:
      - "8080:8080"
    restart: always
    container_name: blocker
    volumes:
      - ./blocker:/app
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
