version: '3.8'

services:
  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: always
    container_name: backend
    volumes:
      - ./backend:/app
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  dnsmasq:
    image: 4km3/dnsmasq:latest
    restart: always
    ports:
      - "8000:8000"
    container_name: dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
