version: '3.3'

services:
  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: always
    container_name: backend
    volumes:
      - ./backend:/app
  mongodb:
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
